<a href="https://colab.research.google.com/github/puzlike/expert-octo-telegram/blob/main/csv_merge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
f1 = pd.read_csv('f1.csv')
f1

     name  ID  p1
0  tanaka   1  aa
1    sato   2  ax
2  suzuki   3  cf

In [6]:
f2 = pd.read_csv('f2.csv')
f2

     name  p2
0  tanaka  ff
1    sato  ee
2    hoso  gh

In [7]:
f3 = pd.read_csv('f3.csv')
f3

     name  p3
0  tanaka  xx
1    sato  tt
2  suzuki  aa
3    hoso  ll

In [18]:
newf = pd.merge(f1, f2, on="name", how="outer")
newf = pd.merge(newf, f3, on="name", how="outer" )
newf.to_csv('newf.csv', index=False)