<a href="https://colab.research.google.com/github/puzlike/expert-octo-telegram/blob/main/rank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
time_data = pd.read_excel('選手名_タイム.xlsx')
time_data

    選手名    タイム
0  選手A   3.368
1  選手B   3.406
2  選手C   3.417
3  選手D   3.417
4  選手E   3.438
5   選手F  3.494
6   選手G  3.471
7  選手H   3.466

In [19]:
time_data['順位'] = time_data['タイム'].rank(method='min').astype(int).astype(str) + "位"
time_data

    選手名    タイム  順位
0  選手A   3.368  1位
1  選手B   3.406  2位
2  選手C   3.417  3位
3  選手D   3.417  3位
4  選手E   3.438  5位
5   選手F  3.494  8位
6   選手G  3.471  7位
7  選手H   3.466  6位

In [20]:
point = [
    ['1位', '10点'],
    ['2位', '8点'],
    ['3位', '6点'],
    ['4位', '5点'],
    ['5位', '4点'],
    ['6位', '3点'],
    ['7位', '2点'],
    ['8位', '1点']
]
point = pd.DataFrame(point, columns=['順位', '得点'])
point

   順位   得点
0  1位  10点
1  2位   8点
2  3位   6点
3  4位   5点
4  5位   4点
5  6位   3点
6  7位   2点
7  8位   1点

In [21]:
time_data = pd.merge(time_data, point, on='順位', how='left')
time_data

    選手名    タイム  順位   得点
0  選手A   3.368  1位  10点
1  選手B   3.406  2位   8点
2  選手C   3.417  3位   6点
3  選手D   3.417  3位   6点
4  選手E   3.438  5位   4点
5   選手F  3.494  8位   1点
6   選手G  3.471  7位   2点
7  選手H   3.466  6位   3点